// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnjLgo3uwClhSISRlfOnqSQFLy6W46ef0',
    appId: '1:288513099403:web:29c73ccdc6fe986d52368e',
    messagingSenderId: '288513099403',
    projectId: 'challenge-five',
    authDomain: 'challenge-five.firebaseapp.com',
    storageBucket: 'challenge-five.appspot.com',
    measurementId: 'G-D1GMK2DDKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWHFjWXlGD3hIa7WLJ5wh5i5focB-o6Kw',
    appId: '1:288513099403:android:3e7000a6733b194552368e',
    messagingSenderId: '288513099403',
    projectId: 'challenge-five',
    storageBucket: 'challenge-five.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOPjDfTUdj2xrW2x6PgnttUwCm-KkMwCQ',
    appId: '1:288513099403:ios:4c01f8b9c6e8886452368e',
    messagingSenderId: '288513099403',
    projectId: 'challenge-five',
    storageBucket: 'challenge-five.appspot.com',
    iosClientId: '288513099403-jfnfg330vnptpi94ciib8ei3b90ip5o2.apps.googleusercontent.com',
    iosBundleId: 'com.example.appChallengeFive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOPjDfTUdj2xrW2x6PgnttUwCm-KkMwCQ',
    appId: '1:288513099403:ios:4c01f8b9c6e8886452368e',
    messagingSenderId: '288513099403',
    projectId: 'challenge-five',
    storageBucket: 'challenge-five.appspot.com',
    iosClientId: '288513099403-jfnfg330vnptpi94ciib8ei3b90ip5o2.apps.googleusercontent.com',
    iosBundleId: 'com.example.appChallengeFive',
  );
}
